# Generated by Django 4.0 on 2023-07-08 15:37

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Oshxona nomi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=50, verbose_name='Oshxona nomi'))),
                ('image', models.ImageField(upload_to='images/kitchen-images/', verbose_name='Oshxona Logosi')),
                ('description', models.TextField(verbose_name='Oshxona haqida malumot')),
                ('status', models.BooleanField(default=True, verbose_name='Aktivlik holati')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='Foydalanuchi')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Lavozim nomi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('status', models.BooleanField(default=True, verbose_name='Aktivlik holati')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sanasi")),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kitchen', verbose_name='Oshxona')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('name', models.CharField(max_length=30, verbose_name='Ism')),
                ('surname', models.CharField(max_length=30, verbose_name='Familiya')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=(models.CharField(max_length=30, verbose_name='Ism'), models.CharField(max_length=30, verbose_name='Familiya')))),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Maosh')),
                ('percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ulush Foizda (ixtiyoriy)')),
                ('oshxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kitchen', verbose_name='Oshxona')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.position', verbose_name='Lavozimi')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
    ]
