# Generated by Django 4.0 on 2023-07-08 15:45

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kitchen_position_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqti"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('oshxona', 'created')),
        ),
    ]
