# Generated by Django 4.0 on 2023-07-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_activated_date_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Maosh (ixtiyoriy)'),
        ),
    ]
