# Generated by Django 4.0 on 2023-07-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='outputitem',
            old_name='product',
            new_name='name',
        ),
    ]
