# Generated by Django 4.0 on 2023-07-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0003_alter_output_cost_alter_outputitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputitem',
            name='output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outputs.output'),
        ),
    ]
